
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO & esptool
        run: |
          pip install --upgrade platformio esptool

      - name: Build firmware (PlatformIO)
        run: |
          pio run -e esp32dev

      - name: Collect artifacts
        shell: bash
        run: |
          set -e
          BUILD_DIR=.pio/build/esp32dev
          mkdir -p dist
          cp "$BUILD_DIR/firmware.bin" dist/spotweldingplus-app.bin
          BOOT=$(ls "$BUILD_DIR"/bootloader*.bin | head -n1 || true)
          PART=$(ls "$BUILD_DIR"/partitions*.bin | head -n1 || true)
          if [ -n "$BOOT" ] && [ -n "$PART" ]; then
            cp "$BOOT" dist/bootloader.bin
            cp "$PART" dist/partitions.bin
            esptool.py --chip esp32 merge_bin               -o dist/spotweldingplus-merged.bin               --flash_mode dio --flash_freq 40m --flash_size 4MB               0x1000 dist/bootloader.bin 0x8000 dist/partitions.bin 0x10000 dist/spotweldingplus-app.bin
          fi
          cp "$BUILD_DIR/firmware.elf" dist/spotweldingplus.elf || true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
